services:
  project-name:
    build:
      context: .
    container_name: project-name
    stdin_open: true
    volumes:
      - project-name-data:/workspace
      - devcontainer-shared-data:/var/lib/devcontainer

volumes:
  project-name-data:
    name: project-name-data
  devcontainer-shared-data:
    name: devcontainer-shared-data
