services:
  project-name:
    build:
      context: .
    container_name: project-name
    stdin_open: true
    volumes:
      - project-name-workspace:/workspace

volumes:
  agents-data:
    name: agents-data
  claude-auth-data:
    name: claude-auth-data
  codex-auth-data:
    name: codex-auth-data
  project-name-workspace:
